defaultContentLanguage = "en"
baseURL = "https://appleloveme.github.io/"
languageCode = "zh-cmn-Hans"
title = "Wecome to ALM Blog"
theme = "dream"
enableRobotsTXT = true
hasCJKLanguage = true
[params]
  # background = "black"
  backgroundImage = "https://tva1.sinaimg.cn/large/007S8ZIlly1gfh8j80hrkj30zk0k0wez.jpg"
  linkColor = "seagreen"

  author = "alm"
  description = "Do yourself!"
  avatar = "https://tva1.sinaimg.cn/large/007S8ZIlly1gfgleiguq0j30kv0kv3z7.jpg"
  motto = "年轻人的焦虑，在于把欲望当做志气"

  email = "dengyifan98@gmail.com"
  github = "appleloveme"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true


[params.valine]
  enable = true
  appId = 'BygvxFkkutypYkx96cxKakAH-gzGzoHsz'
  appKey = 'amDtpgmBqUeq7AjlFPQfrtYL'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'robohash'
  placeholder = '分享你的想法,拥抱更大的世界(Markdown Support!)'
  visitor = true
